### ISSUE TITLE
[tests] callbacks/* - Utilize recursive instantiation or find alternative method

### ISSUE THREAD

**Issue by romesco** [romesco/hydra-lightning#2]
Quoting @omry:

Something like:
```
trainer:
  _target_: Trainer
  callback:
    _target_: hydra.utils.get_method
    path: my_callback
```

Another possibility using existing hydra methods:
```
_target_ : foo.Foo
callback: ${get_function:my_callback}
```
